# Generated by Django 6.0.5 on 2026-07-09 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_particulate_matter', models.BooleanField()),
                ('is_lux', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_meet_je_stad.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('firmware_version', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('lux', models.FloatField(null=True)),
                ('supply', models.FloatField()),
                ('battery', models.FloatField(null=True)),
                ('pm25', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('extra', models.JSONField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_meet_je_stad.sensor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sensor', 'timestamp'), name='unique_measurement')],
            },
        ),
    ]
