# Generated by Django 6.0.5 on 2026-07-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_particulate_matter', models.BooleanField()),
                ('last_measurement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('firmware_version', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('lux', models.FloatField(null=True)),
                ('supply', models.FloatField()),
                ('battery', models.FloatField(null=True)),
                ('pm25', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('extra1', models.FloatField(null=True)),
                ('extra2', models.FloatField(null=True)),
                ('extra3', models.FloatField(null=True)),
                ('extra4', models.FloatField(null=True)),
                ('extra5', models.FloatField(null=True)),
                ('extra6', models.FloatField(null=True)),
                ('extra7', models.FloatField(null=True)),
                ('extra8', models.FloatField(null=True)),
                ('extra9', models.FloatField(null=True)),
                ('extra10', models.FloatField(null=True)),
                ('extra11', models.FloatField(null=True)),
                ('extra12', models.FloatField(null=True)),
                ('extra13', models.FloatField(null=True)),
                ('extra14', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_meet_je_stad.sensor')),
            ],
        ),
    ]
