# Generated by Django 6.0 on 2026-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('begin_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('begin_year_perc_rain', models.IntegerField()),
                ('begin_year_amount_rain', models.IntegerField()),
            ],
        ),
    ]
