# Generated by Django 6.0.7 on 2026-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=255, unique=True)),
                ('_begin_year', models.IntegerField()),
                ('_end_year', models.IntegerField()),
                ('_begin_year_perc_rain', models.IntegerField()),
                ('_begin_year_amount_rain', models.IntegerField()),
            ],
        ),
    ]
